"""The GitHub Action packaging.

The point of these tests is INV-4 at the credential layer. The code has no write
path, but code can be changed by accident; a token that cannot write is a
guarantee that survives a bad edit. So the workflow's `permissions:` block is
asserted here as strictly as any code path.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml")

ROOT = Path(__file__).parent.parent
ACTION = ROOT / "action.yml"
WORKFLOW = ROOT / ".github" / "workflows" / "review.yml"


def _load(path: Path) -> dict:  # type: ignore[type-arg]
    return yaml.safe_load(path.read_text())  # type: ignore[no-any-return]


def _run_scripts(path: Path) -> list[str]:
    """Every `run:` script body in a workflow or composite action."""
    doc = _load(path)
    steps = doc.get("runs", {}).get("steps") or []
    for job in (doc.get("jobs") or {}).values():
        steps = steps + (job.get("steps") or [])
    return [s["run"] for s in steps if isinstance(s.get("run"), str)]


class TestWorkflowPermissions:
    def test_the_workflow_declares_permissions_at_all(self) -> None:
        """Omitting the block inherits the repository default, which may be
        write. Silence is not a safe default here."""
        assert "permissions" in _load(WORKFLOW)

    def test_no_permission_is_write(self) -> None:
        """M5's stated criterion: the token has no write scope.

        The agent's autonomy level is 'human reviews output'. A write-scoped
        token would grant the action nothing it uses, and would widen the blast
        radius of any future bug for no benefit.
        """
        perms = _load(WORKFLOW)["permissions"]
        offenders = {k: v for k, v in perms.items() if v != "read"}
        assert offenders == {}, f"write scope granted: {offenders}"

    def test_pull_requests_is_read(self) -> None:
        assert _load(WORKFLOW)["permissions"]["pull-requests"] == "read"

    def test_the_job_has_a_timeout(self) -> None:
        """A hung job costs money and blocks the queue. The orchestrator's
        per-lane deadline is the first defence; this is the backstop."""
        job = _load(WORKFLOW)["jobs"]["review"]
        assert isinstance(job.get("timeout-minutes"), int)
        assert 0 < job["timeout-minutes"] <= 60


class TestActionDefinition:
    def test_action_is_valid_and_named(self) -> None:
        action = _load(ACTION)
        assert action["name"]
        assert action["runs"]["using"] == "composite"

    def test_the_token_input_documents_read_only(self) -> None:
        desc = _load(ACTION)["inputs"]["github-token"]["description"]
        assert "read" in desc.lower()

    def test_offline_mode_is_available_without_a_key(self) -> None:
        """The pipeline must be able to prove itself end to end in CI with no
        credentials — otherwise a missing key silently skips the review."""
        assert "offline" in _load(ACTION)["inputs"]

    def test_the_action_exposes_the_gate_verdict(self) -> None:
        outputs = _load(ACTION)["outputs"]
        assert "verdict" in outputs and "confidence" in outputs and "findings" in outputs

    def test_the_action_does_not_default_to_failing_the_build(self) -> None:
        """This reviewer drafts; it does not gate merges. A noisy first week must
        not block the team — opting in is the user's call."""
        assert _load(ACTION)["inputs"]["fail-on-critical"]["default"] == "false"

    def test_no_step_posts_to_the_pull_request(self) -> None:
        """INV-4 in the packaging, not just the library."""
        text = ACTION.read_text().lower()
        for forbidden in ("gh pr comment", "gh pr review", "/comments", "create_review",
                          "issues/comments", "gh api -x post", "-x post"):
            assert forbidden not in text, f"the action contains a write call: {forbidden}"

    def test_the_reviewer_runs_exactly_once(self) -> None:
        """Regression: the action used to run the full fan-out twice — once for
        `--json` and again for `--draft`.

        That doubled the LLM bill, and because the two invocations are separate
        reviews it could show a human a draft generated by a *different* review
        than the one whose verdict gated the job and whose id the events trace
        reconstructs. One fan-out, all artifacts.
        """
        invocations = [
            line
            for script in _run_scripts(ACTION)
            for line in script.splitlines()
            if re.search(r"\bpr-review\s+run\b", line)
        ]
        assert len(invocations) == 1, f"the reviewer runs {len(invocations)}x: {invocations}"
        assert "--json-out" in invocations[0] and "--draft" in invocations[0]

    def test_a_failed_lane_does_not_abort_the_step(self) -> None:
        """Regression: the second `pr-review run` sat after `set -e` had been
        restored, so an exit-1 (a specialist lane died) killed the step before
        the `::warning::` that exists to tell the human the review is partial.

        Any `pr-review run` must be inside a `set +e` window.
        """
        for script in _run_scripts(ACTION):
            if not re.search(r"\bpr-review\s+run\b", script):
                continue
            guarded = False
            for line in script.splitlines():
                stripped = line.strip()
                if stripped.startswith("set +e"):
                    guarded = True
                elif stripped.startswith("set -e"):
                    guarded = False
                elif re.search(r"\bpr-review\s+run\b", stripped):
                    assert guarded, f"unguarded under `set -e`: {stripped}"

    def test_no_caller_controlled_expression_is_interpolated_into_a_script(self) -> None:
        """GitHub substitutes ${{ }} as raw TEXT before bash parses the script, so
        a caller-controlled value inside `run:` is arbitrary code execution on the
        runner. Such values must arrive as environment variables, which bash
        treats as data whatever they contain.

        `github.action_path` and `github.repository` are set by GitHub itself and
        are not caller-controlled, so they are allowed.
        """
        allowed = {"github.action_path", "github.repository"}
        for path in (ACTION, WORKFLOW):
            for script in _run_scripts(path):
                for expr in re.findall(r"\$\{\{([^}]*)\}\}", script):
                    name = expr.strip()
                    assert name in allowed, (
                        f"{path.name}: caller-controlled ${{{{ {name} }}}} interpolated "
                        f"into a run: script — pass it through env: instead"
                    )

    def test_the_pull_request_number_is_validated_as_numeric(self) -> None:
        """Defence in depth behind the env-var fix: a PR number is an integer."""
        scripts = "\n".join(_run_scripts(ACTION))
        assert "[!0-9]" in scripts, "the PR number is never checked for being numeric"

    def test_no_job_overrides_the_read_only_permissions(self) -> None:
        """A per-job `permissions:` block silently overrides the top-level one.

        Checked on parsed YAML, not raw text: the workflow's comments explain why
        write scope is withheld, and a naive substring match trips on the
        explanation rather than on a real grant.
        """
        wf = _load(WORKFLOW)
        for name, job in wf["jobs"].items():
            perms = job.get("permissions")
            if perms is None:
                continue
            offenders = {k: v for k, v in perms.items() if v != "read"}
            assert offenders == {}, f"job {name} grants write: {offenders}"
