"""Diff parsing — the grounding truth everything else is checked against.

The fixture is generated by real `git diff` and applies cleanly, so the line
numbers asserted here are ground truth, not a restatement of the parser's own
arithmetic. An earlier version of this file joined the added lines into one
string and substring-matched, which asserted nothing about numbering at all —
and let an off-by-N numbering bug ship.
"""

from __future__ import annotations

import time
from pathlib import Path

from prreview.diff import parse_diff

FIXTURE = Path(__file__).parent.parent / "fixtures" / "sample.diff"

# Verified against the working tree the fixture was generated from.
GROUND_TRUTH: dict[tuple[str, str], int] = {
    ("app/db.py", "cur.execute"): 10,
    ("app/db.py", "API_KEY"): 14,
    ("app/client.py", "requests.get"): 7,
    ("app/client.py", "print("): 8,
    ("app/client.py", "TODO"): 12,
}


def _diff():  # type: ignore[no-untyped-def]
    return parse_diff(FIXTURE.read_text())


def test_parses_both_files() -> None:
    assert sorted(_diff().paths) == ["app/client.py", "app/db.py"]


def test_added_lines_carry_the_true_file_line_numbers() -> None:
    """The assertion that matters: parser numbering == real file numbering."""
    diff = _diff()
    checked = 0
    for (path, needle), expected in GROUND_TRUTH.items():
        fd = diff.by_path(path)
        assert fd is not None, f"{path} missing from parsed diff"
        hits = [ln for ln, code in fd.added_lines.items() if needle in code]
        assert hits == [expected], f"{path} '{needle}': parser said {hits}, truth {expected}"
        checked += 1
    assert checked == len(GROUND_TRUTH)


def test_blank_context_line_without_leading_space_still_advances_numbering() -> None:
    """B1 regression.

    git writes a blank context line as a single space, but editors, mail clients
    and copy-paste strip trailing whitespace. If "" is not treated as a context
    line, every subsequent line number shifts up by one.
    """
    stripped = "\n".join(
        line.rstrip() if line.strip() == "" else line
        for line in FIXTURE.read_text().splitlines()
    )
    diff = parse_diff(stripped)
    for (path, needle), expected in GROUND_TRUTH.items():
        fd = diff.by_path(path)
        assert fd is not None
        hits = [ln for ln, code in fd.added_lines.items() if needle in code]
        assert hits == [expected], (
            f"whitespace-stripped diff shifted {path} '{needle}' to {hits}, truth {expected}"
        )


def test_no_newline_marker_does_not_advance_numbering() -> None:
    text = (
        "--- a/x.py\n+++ b/x.py\n@@ -1,2 +1,3 @@\n a\n+b\n\\ No newline at end of file\n+c\n"
    )
    fd = parse_diff(text).by_path("x.py")
    assert fd is not None
    assert sorted(fd.added_lines) == [2, 3]


def test_added_line_that_looks_like_a_file_header_is_not_one() -> None:
    """N4 regression: '++ b/evil.py' inside a hunk is content, not a header."""
    text = "--- a/real.py\n+++ b/real.py\n@@ -1,1 +1,3 @@\n x = 1\n+++ b/evil.py\n+y = 2\n"
    diff = parse_diff(text)
    assert diff.paths == ["real.py"], f"phantom file invented: {diff.paths}"
    fd = diff.by_path("real.py")
    assert fd is not None
    assert any("y = 2" in c for c in fd.added_lines.values()), "real content was lost"


def test_deleted_file_is_skipped() -> None:
    text = "--- a/gone.py\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-x = 1\n"
    assert parse_diff(text).files == []


def test_multiple_hunks_in_one_file_are_numbered_independently() -> None:
    text = (
        "--- a/m.py\n+++ b/m.py\n"
        "@@ -1,2 +1,3 @@\n a\n+b\n c\n"
        "@@ -50,2 +51,3 @@\n d\n+e\n f\n"
    )
    fd = parse_diff(text).by_path("m.py")
    assert fd is not None
    assert sorted(fd.added_lines) == [2, 52]


class TestGroundingPredicate:
    """INV-3's predicate is containment, not overlap."""

    def test_range_inside_a_hunk_is_grounded(self) -> None:
        assert _diff().is_grounded("app/db.py", 10, 10) is True

    def test_unknown_file_is_not_grounded(self) -> None:
        assert _diff().is_grounded("does/not/exist.py", 1, 1) is False

    def test_inverted_range_is_not_grounded(self) -> None:
        assert _diff().is_grounded("app/db.py", 20, 10) is False

    def test_straddling_range_is_not_grounded(self) -> None:
        """B3 regression: the bypass that let a hallucinated location through.

        Neither endpoint is inside the hunk; the range merely spans it. Under the
        old overlap rule this returned True and the CLI printed 'app/db.py:1'.
        """
        assert _diff().is_grounded("app/db.py", 1, 100000) is False

    def test_partially_overlapping_range_is_not_grounded(self) -> None:
        diff = _diff()
        fd = diff.by_path("app/db.py")
        assert fd is not None
        hunk = fd.hunks[0]
        assert diff.is_grounded("app/db.py", hunk.start - 5, hunk.start + 1) is False
        assert diff.is_grounded("app/db.py", hunk.end - 1, hunk.end + 5) is False

    def test_absurd_range_returns_immediately(self) -> None:
        """B3 regression: containment is O(hunks), not O(range size).

        The old implementation enumerated every line, so a model emitting
        line_end: 10_000_000 bought seconds of dead spin per finding.
        """
        diff = _diff()
        started = time.monotonic()
        assert diff.is_grounded("app/db.py", 5_000_000, 10_000_000) is False
        assert time.monotonic() - started < 0.1
