"""Diff parsing — the grounding truth everything else is checked against.

The fixture is generated by real `git diff` and applies cleanly, so the line
numbers asserted here are ground truth, not a restatement of the parser's own
arithmetic. An earlier version of this file joined the added lines into one
string and substring-matched, which asserted nothing about numbering at all —
and let an off-by-N numbering bug ship.
"""

from __future__ import annotations

import time
from pathlib import Path

import pytest

from prreview.diff import parse_diff

FIXTURE = Path(__file__).parent.parent / "fixtures" / "sample.diff"

# Verified against the working tree the fixture was generated from.
GROUND_TRUTH: dict[tuple[str, str], int] = {
    ("app/db.py", "cur.execute"): 10,
    ("app/db.py", "API_KEY"): 14,
    ("app/client.py", "requests.get"): 7,
    ("app/client.py", "print("): 8,
    ("app/client.py", "TODO"): 12,
}


def _diff():  # type: ignore[no-untyped-def]
    return parse_diff(FIXTURE.read_text())


def test_parses_both_files() -> None:
    assert sorted(_diff().paths) == ["app/client.py", "app/db.py"]


def test_added_lines_carry_the_true_file_line_numbers() -> None:
    """The assertion that matters: parser numbering == real file numbering."""
    diff = _diff()
    checked = 0
    for (path, needle), expected in GROUND_TRUTH.items():
        fd = diff.by_path(path)
        assert fd is not None, f"{path} missing from parsed diff"
        hits = [ln for ln, code in fd.added_lines.items() if needle in code]
        assert hits == [expected], f"{path} '{needle}': parser said {hits}, truth {expected}"
        checked += 1
    assert checked == len(GROUND_TRUTH)


def test_blank_context_line_without_leading_space_still_advances_numbering() -> None:
    """B1 regression.

    git writes a blank context line as a single space, but editors, mail clients
    and copy-paste strip trailing whitespace. If "" is not treated as a context
    line, every subsequent line number shifts up by one.
    """
    stripped = "\n".join(
        line.rstrip() if line.strip() == "" else line
        for line in FIXTURE.read_text().splitlines()
    )
    diff = parse_diff(stripped)
    for (path, needle), expected in GROUND_TRUTH.items():
        fd = diff.by_path(path)
        assert fd is not None
        hits = [ln for ln, code in fd.added_lines.items() if needle in code]
        assert hits == [expected], (
            f"whitespace-stripped diff shifted {path} '{needle}' to {hits}, truth {expected}"
        )


def test_no_newline_marker_does_not_advance_numbering() -> None:
    text = (
        "--- a/x.py\n+++ b/x.py\n@@ -1,2 +1,3 @@\n a\n+b\n\\ No newline at end of file\n+c\n"
    )
    fd = parse_diff(text).by_path("x.py")
    assert fd is not None
    assert sorted(fd.added_lines) == [2, 3]


def test_added_line_that_looks_like_a_file_header_is_not_one() -> None:
    """N4 regression: '++ b/evil.py' inside a hunk is content, not a header."""
    text = "--- a/real.py\n+++ b/real.py\n@@ -1,1 +1,3 @@\n x = 1\n+++ b/evil.py\n+y = 2\n"
    diff = parse_diff(text)
    assert diff.paths == ["real.py"], f"phantom file invented: {diff.paths}"
    fd = diff.by_path("real.py")
    assert fd is not None
    assert any("y = 2" in c for c in fd.added_lines.values()), "real content was lost"


def test_deleted_line_starting_with_dash_dash_does_not_end_the_hunk() -> None:
    """BD-1 regression — a regression introduced by the fix for N4.

    git renders a deleted line whose content starts with "-- " (SQL comment,
    email signature) as "--- <content>", which a prefix heuristic cannot tell
    from a file header. Ending the hunk there let the next added line beginning
    "++ " be read as a new file: a phantom path was invented and the real file's
    line — a hardcoded credential, in the security lane — was silently lost.
    This diff is a valid patch; `git apply --check` accepts it.
    """
    text = (
        "--- a/mig.sql\n+++ b/mig.sql\n"
        "@@ -1,4 +1,5 @@\n"
        "--- seed the users table\n"
        " SELECT 1;\n"
        " keep_me = 1\n"
        "+++ b/phantom.py\n"
        '+password = "leaked"\n'
        " BASE = 2\n"
    )
    diff = parse_diff(text)
    assert diff.paths == ["mig.sql"], f"phantom file invented: {diff.paths}"
    fd = diff.by_path("mig.sql")
    assert fd is not None
    added = sorted(fd.added_lines.items())
    assert added == [(3, "++ b/phantom.py"), (4, 'password = "leaked"')], added


def test_hunk_body_extent_comes_from_the_header_counts() -> None:
    """Content after a hunk's declared length is structure again, not body."""
    text = (
        "--- a/a.py\n+++ b/a.py\n@@ -1,1 +1,2 @@\n x\n+y\n"
        "--- a/b.py\n+++ b/b.py\n@@ -1,1 +1,2 @@\n p\n+q\n"
    )
    diff = parse_diff(text)
    assert diff.paths == ["a.py", "b.py"]
    for path, want in (("a.py", "y"), ("b.py", "q")):
        fd = diff.by_path(path)
        assert fd is not None
        assert list(fd.added_lines.values()) == [want]


SEPARATORS = ["\x0b", "\x0c", "\x1c", "\x1d", "\x1e", "\x85", " ", " "]


@pytest.mark.parametrize("sep", SEPARATORS, ids=lambda s: f"U+{ord(s):04X}")
def test_unicode_line_separators_in_content_do_not_split_a_line(sep: str) -> None:
    """Round-3 blocking regression.

    str.splitlines() breaks on these, but in a diff they are *content*: a form-feed
    page break is a documented convention in GNU C, Emacs Lisp and PEP 8, and
    U+2028 appears in JS/JSON strings. Splitting one added line into two truncates
    its recorded content, shifts every later line number, and corrupts the body
    counters. Worse than the prefix bug it resembles: the shifted line still lands
    inside the declared hunk, so is_grounded() returns True and INV-3 goes green
    on a mis-located finding.
    """
    text = f"--- a/f.c\n+++ b/f.c\n@@ -1,2 +1,4 @@\n ctx\n+int a;{sep}int b;\n+SECRET = 1\n ctx2\n"
    fd = parse_diff(text).by_path("f.c")
    assert fd is not None
    assert sorted(fd.added_lines) == [2, 3], f"line split by {sep!r}"
    assert fd.added_lines[2] == f"int a;{sep}int b;", "content was truncated"
    assert fd.added_lines[3] == "SECRET = 1", "later line shifted"


def test_crlf_diff_parses_identically() -> None:
    text = "--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,2 @@\n ctx\n+added\n"
    fd = parse_diff(text.replace("\n", "\r\n")).by_path("f.py")
    assert fd is not None
    assert fd.added_lines == {2: "added"}


def test_over_declared_hunk_header_does_not_ground_unseen_lines() -> None:
    """Round-3 blocking regression: false ACCEPT.

    Truncated patches are ordinary input — GitHub truncates the per-file `patch`
    field on large files. The header claimed 220 new-side lines; the body had two.
    Trusting the header let is_grounded() accept line 219, which the parser never
    saw, contradicting M1's "verified present in the parsed diff".
    """
    diff = parse_diff("--- a/big.py\n+++ b/big.py\n@@ -1,200 +1,220 @@\n ctx\n+x=1\n")
    fd = diff.by_path("big.py")
    assert fd is not None
    assert [(h.start, h.end) for h in fd.hunks] == [(1, 2)]
    assert diff.is_grounded("big.py", 219, 220) is False
    assert diff.is_grounded("big.py", 2, 2) is True


def test_under_declared_hunk_header_still_grounds_lines_it_read() -> None:
    """Round-3 blocking regression: false REJECT.

    The parser read line 2 and showed it to the model; rejecting a correct
    finding on it as 'ungrounded' punishes the model for the parser's arithmetic.
    """
    diff = parse_diff("--- a/u.py\n+++ b/u.py\n@@ -1,3 +1,1 @@\n ctx\n+y=2\n ctx2\n")
    fd = diff.by_path("u.py")
    assert fd is not None
    assert fd.added_lines == {2: "y=2"}
    assert diff.is_grounded("u.py", 2, 2) is True


def test_pure_deletion_hunk_grounds_nothing() -> None:
    diff = parse_diff("--- a/d.py\n+++ b/d.py\n@@ -1,3 +0,0 @@\n-a\n-b\n-c\n")
    fd = diff.by_path("d.py")
    assert fd is not None
    assert fd.hunks == []
    assert diff.is_grounded("d.py", 1, 1) is False


def test_quoted_non_ascii_path_is_decoded() -> None:
    text = '--- "a/wei\\303\\237.txt"\n+++ "b/wei\\303\\237.txt"\n@@ -1,1 +1,2 @@\n ctx\n+x\n'
    assert parse_diff(text).paths == ["weiß.txt"]


def test_combined_body_cannot_invent_a_phantom_path() -> None:
    """A combined body line starting '+ ' renders as '+++ …'."""
    text = "--- a/m.py\n+++ b/m.py\n@@@ -1,3 -1,3 +1,4 @@@\n  ctx\n+ bullet\n++added\n"
    assert parse_diff(text).paths == []


def test_combined_and_normal_file_in_one_diff_keeps_the_normal_one() -> None:
    text = (
        "diff --git a/m.py b/m.py\n--- a/m.py\n+++ b/m.py\n@@@ -1,3 -1,3 +1,4 @@@\n  ctx\n++added\n"
        "diff --git a/ok.py b/ok.py\n--- a/ok.py\n+++ b/ok.py\n@@ -1,1 +1,2 @@\n ctx\n+real=1\n"
    )
    diff = parse_diff(text)
    assert diff.paths == ["ok.py"]
    fd = diff.by_path("ok.py")
    assert fd is not None
    assert fd.added_lines == {2: "real=1"}


def test_combined_merge_diff_is_refused_not_misparsed() -> None:
    """A three-way combined diff has no two-dot post-image; refuse it.

    Refusing means the file gets no hunks, so nothing can be grounded against it
    and no finding is manufactured from a misread body.
    """
    text = "--- a/m.py\n+++ b/m.py\n@@@ -1,3 -1,3 +1,4 @@@\n  ctx\n++added\n"
    assert parse_diff(text).files == []


def test_deleted_file_is_skipped() -> None:
    text = "--- a/gone.py\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-x = 1\n"
    assert parse_diff(text).files == []


def test_multiple_hunks_in_one_file_are_numbered_independently() -> None:
    text = (
        "--- a/m.py\n+++ b/m.py\n"
        "@@ -1,2 +1,3 @@\n a\n+b\n c\n"
        "@@ -50,2 +51,3 @@\n d\n+e\n f\n"
    )
    fd = parse_diff(text).by_path("m.py")
    assert fd is not None
    assert sorted(fd.added_lines) == [2, 52]


class TestGroundingPredicate:
    """INV-3's predicate is containment, not overlap."""

    def test_range_inside_a_hunk_is_grounded(self) -> None:
        assert _diff().is_grounded("app/db.py", 10, 10) is True

    def test_unknown_file_is_not_grounded(self) -> None:
        assert _diff().is_grounded("does/not/exist.py", 1, 1) is False

    def test_inverted_range_is_not_grounded(self) -> None:
        assert _diff().is_grounded("app/db.py", 20, 10) is False

    def test_straddling_range_is_not_grounded(self) -> None:
        """B3 regression: the bypass that let a hallucinated location through.

        Neither endpoint is inside the hunk; the range merely spans it. Under the
        old overlap rule this returned True and the CLI printed 'app/db.py:1'.
        """
        assert _diff().is_grounded("app/db.py", 1, 100000) is False

    def test_partially_overlapping_range_is_not_grounded(self) -> None:
        diff = _diff()
        fd = diff.by_path("app/db.py")
        assert fd is not None
        hunk = fd.hunks[0]
        assert diff.is_grounded("app/db.py", hunk.start - 5, hunk.start + 1) is False
        assert diff.is_grounded("app/db.py", hunk.end - 1, hunk.end + 5) is False

    def test_absurd_range_returns_immediately(self) -> None:
        """B3 regression: containment is O(hunks), not O(range size).

        The old implementation enumerated every line, so a model emitting
        line_end: 10_000_000 bought seconds of dead spin per finding.
        """
        diff = _diff()
        started = time.monotonic()
        assert diff.is_grounded("app/db.py", 5_000_000, 10_000_000) is False
        assert time.monotonic() - started < 0.1
